export const HOOK_SUBSCRIBE_REQUEST = 'HOOK_SUBSCRIBE_REQUEST';
export const HOOK_SUBSCRIBE_SUCCESS = 'HOOK_SUBSCRIBE_SUCCESS';
export const HOOK_SUBSCRIBE_FAIL = 'HOOK_SUBSCRIBE_FAIL';
export const HOOK_UNSUBSCRIBE_REQUEST = 'HOOK_UNSUBSCRIBE_REQUEST';
export const HOOK_SUBSCRIBE_RESET = 'HOOK_SUBSCRIBE_RESET';

export const HOOK_UNSUBSCRIBE_SUCCESS = 'HOOK_UNSUBSCRIBE_SUCCESS';
export const HOOK_UNSUBSCRIBE_FAIL = 'HOOK_UNSUBSCRIBE_FAIL';

export const HOOK_API_KEY_REQUEST = 'HOOK_API_KEY_REQUEST';
export const HOOK_API_KEY_SUCCESS = 'HOOK_API_KEY_SUCCESS';
export const HOOK_API_KEY_FAIL = 'HOOK_API_KEY_FAIL';
